#!/bin/sh
############################################################ LICENSE
#
# Copyright (c) 2026 Devin Teske <dteske@FreeBSD.org>
#
# SPDX-License-Identifier: BSD-2-Clause
#
############################################################ IDENT(1)
#
# $Title: Grab listener chords in openbox $
# $Copyright: 2026 Devin Teske. All rights reserved. $
# $FrauBSD: bhotkeys/libexec/bhotkeys-openbox-apply 2026-10-04 11:21:26 -0700 Devin Teske $
#
############################################################ INFORMATION
#
# Grab listener chords in openbox so the focused client does not
# see them. Each new chord runs true. A keybind openbox already
# has is left alone. An lxde or lxqt session is not this script.
# Missing openbox is not an error.
#
############################################################ INCLUDES

. "${0%/*}/bhotkeys-prefix.subr" || exit
. "$PREFIX/libexec/bhotkeys/bhotkeys-seq.subr" || exit
. "$PREFIX/libexec/bhotkeys/bhotkeys-openbox.subr" || exit

############################################################ GLOBALS

bh_wm=openbox

############################################################ FUNCTIONS

openbox_up()
{
	proc_eq lxsession && return 1
	proc_eq lxqt-session && return 1
	proc_eq openbox
}


rc_path()
{
	if [ "$XDG_CONFIG_HOME" ]; then
		rc_file="$XDG_CONFIG_HOME/openbox/rc.xml"
	else
		rc_file="$HOME/.config/openbox/rc.xml"
	fi
}


seed_rc()
{
	[ -f "$rc_file" ] && return 0
	copy_first "$rc_file" \
		"$OPENBOX_PREFIX/etc/xdg/openbox/rc.xml" \
		"$OPENBOX_PREFIX/share/openbox/rc.xml" \
		/etc/xdg/openbox/rc.xml
}


main()
{
	case "$1" in
	--wait) apply_wait openbox_up || exit 0 ;;
	*) openbox_up || exit 0
	esac
	[ "$HOME" ] || exit 0
	bh_resolve || exit 0
	rc_path
	seed_rc || exit 0
	ob_apply
}

case "$0" in
*bhotkeys-openbox-apply) main "$@" ;;
esac

################################################################################
# END
################################################################################
