#!/bin/sh
############################################################ LICENSE
#
# Copyright (c) 2026 Devin Teske <dteske@FreeBSD.org>
#
# SPDX-License-Identifier: BSD-2-Clause
#
############################################################ IDENT(1)
#
# $Title: Grab listener chords in LXDE $
# $Copyright: 2026 Devin Teske. All rights reserved. $
# $FrauBSD: bhotkeys/libexec/bhotkeys-lxde-apply 2026-10-04 11:21:26 -0700 Devin Teske $
#
############################################################ INFORMATION
#
# Grab listener chords in LXDE so the focused client does not see
# them. LXDE's window manager is openbox, reading lxde-rc.xml.
# Each new chord runs true. A keybind already in that file is left
# alone. Missing lxsession is not an error.
#
############################################################ INCLUDES

. "${0%/*}/bhotkeys-prefix.subr" || exit
. "$PREFIX/libexec/bhotkeys/bhotkeys-seq.subr" || exit
. "$PREFIX/libexec/bhotkeys/bhotkeys-openbox.subr" || exit

############################################################ GLOBALS

bh_wm=lxde

############################################################ FUNCTIONS

lxde_up()
{
	proc_eq lxsession
}


rc_path()
{
	if [ "$XDG_CONFIG_HOME" ]; then
		rc_file="$XDG_CONFIG_HOME/openbox/lxde-rc.xml"
	else
		rc_file="$HOME/.config/openbox/lxde-rc.xml"
	fi
}


seed_rc()
{
	[ -f "$rc_file" ] && return 0
	copy_first "$rc_file" \
		"$LXDE_PREFIX/share/lxde/openbox/rc.xml" \
		"$LXDE_PREFIX/etc/xdg/openbox/lxde-rc.xml" \
		"$LXDE_PREFIX/etc/xdg/openbox/rc.xml" \
		/etc/xdg/openbox/rc.xml
}


main()
{
	case "$1" in
	--wait) apply_wait lxde_up || exit 0 ;;
	*) lxde_up || exit 0
	esac
	[ "$HOME" ] || exit 0
	bh_resolve || exit 0
	rc_path
	seed_rc || exit 0
	ob_apply
}

case "$0" in
*bhotkeys-lxde-apply) main "$@" ;;
esac

################################################################################
# END
################################################################################
