#!/bin/sh
############################################################ LICENSE
#
# Copyright (c) 2026 Devin Teske <dteske@FreeBSD.org>
#
# SPDX-License-Identifier: BSD-2-Clause
#
############################################################ IDENT(1)
#
# $Title: Push listen-0 chords into bvwm $
# $Copyright: 2026 Devin Teske. All rights reserved. $
# $FrauBSD: bhotkeys/libexec/bhotkeys-bvwm-apply 2026-10-03 18:50:50 -0700 Devin Teske $
#
############################################################ INFORMATION
#
# Push listen-0 chords into the running bvwm instance. bhotkeys does not listen
# for these; bvwm does. Missing MFL is not an error.
#
############################################################ GLOBALS

seq_lib="${0%/*}/bhotkeys-seq.subr"
[ -f "$seq_lib" ] || seq_lib="${0%/*}/../../bhotkeys/bhotkeys-seq.subr"
[ -f "$seq_lib" ] || seq_lib=/usr/local/bhotkeys/bhotkeys-seq.subr
[ -f "$seq_lib" ] || exit 0
. "$seq_lib"

############################################################ FUNCTIONS

bvwm_up()
{
	proc_eq bvwm
}

############################################################ MAIN

case "$1" in
--wait) apply_wait bvwm_up || exit 0 ;;
*) bvwm_up || exit 0
esac
bh_resolve || exit 0
have FvwmCommand || exit 0

sock="${FVWMMFL_SOCKET:-/tmp/fvwmmfl/fvwm_mfl_:0.sock}"
[ -S "$sock" ] || exit 0

"$BH" --print-keys bvwm |
	while IFS= read -r line; do
		[ "$line" ] || continue
		quietly FvwmCommand -f "$sock" "$line" || : errors ignored
	done

################################################################################
# END
################################################################################
